In [1]:
# load datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_style('darkgrid')

alpha08 = pd.read_csv('data_08_v2.csv', sep = ',')
alpha18 = pd.read_csv('data_18_v2.csv', sep = ',')

In [2]:
alpha08.dtypes

model                    object
displ                   float64
cyl                      object
trans                    object
drive                    object
fuel                     object
veh_class                object
air_pollution_score      object
city_mpg                 object
hwy_mpg                  object
cmb_mpg                  object
greenhouse_gas_score     object
smartway                 object
dtype: object

In [10]:
alpha18.dtypes

model                    object
displ                   float64
cyl                     float64
trans                    object
drive                    object
fuel                     object
veh_class                object
air_pollution_score       int64
city_mpg                 object
hwy_mpg                  object
cmb_mpg                  object
greenhouse_gas_score      int64
smartway                 object
dtype: object

In [4]:
alpha08.cyl.unique()

array(['(6 cyl)', '(4 cyl)', '(12 cyl)', '(8 cyl)', '(10 cyl)',
       '(16 cyl)', '(5 cyl)', '(2 cyl)'], dtype=object)

In [5]:
alpha18.cyl.unique()

array([ 6.,  4.,  5., 12., 16.,  8.,  3.])

In [6]:
alpha08.air_pollution_score.unique()

array(['7', '6', '9.5', '9', '6/4'], dtype=object)

In [7]:
alpha18.air_pollution_score.unique()

array([3, 1, 7, 5, 6], dtype=int64)

In [8]:
alpha08.greenhouse_gas_score.unique()

array(['4', '5', '6', '7', '0', '1', '3', '2', '8', '9', '10', '7/6'],
      dtype=object)

In [9]:
alpha18.greenhouse_gas_score.unique()

array([ 5,  4,  6,  7,  2,  1, 10,  3,  9,  8], dtype=int64)