https://numpy.org/

### Importing NumPy

In [ ]:
import numpy as np

### Scalars

In [2]:
s = np.array(5)

In [3]:
s.shape

()

In [4]:
x = s + 3

### Vectors

In [5]:
v = np.array([1,2,3])

In [6]:
x = v[1]

In [7]:
v[1:]

array([2, 3])

### Matrices

In [8]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [9]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Tensors

In [10]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [11]:
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [12]:
t.shape

(3, 3, 2, 1)

### Changing Shapes

In [13]:
v = np.array([1,2,3,4])

In [14]:
x = v.reshape(1,4)

In [15]:
x = v.reshape(4,1)

In [16]:
x = v[None, :]

In [17]:
x = v[:, None]